modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="All Rights Reserved"
credits="vincentmet, TheBritishBotherhood, MechWarrior99" #optional
[[mods]] #mandatory
modId="rhodonite" #mandatory
version="1.18.2-1.0.0" #mandatory
displayName="Rhodonite" #mandatory
description="Rhodonite!!!"